config/routes.rb
Rails.application.routes.draw do

  # # ユーザー用
    devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
   }
  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
   sessions: "admin/sessions"
  }

 scope module: :public do
  root :to =>"homes#top"

  #ユーザー
   resources :users, only: [:show,:edit,:update,:destroy,:create]
  #商品
   resources :items, only: [:show, :index] do
    #コメント機能
    resources :item_comments, only: [:create, :destroy]
    #いいね機能
    resource :favorites, only: [:create, :destroy]
   end
 end

 namespace :admin do
  root :to =>"homes#top"
  # ジャンル
   resources :genres, only: [:create, :index, :update, :edit,]
  # 商品
   resources :items, only: [:new, :show, :create, :edit, :index, :update]
 end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
   has_many :users
   has_many :item_comments, dependent: :destroy
   has_many :favorites, dependent: :destroy
   has_many :favorite_users, through: :favorites, source: :user
   has_one_attached :image

   validates :image, presence: true
   validates :name, presence: true
   validates :explanation, presence: true
   validates :genre_id, presence: true

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
   def index
     @items = Item.all
   end

   def new
     @item = Item.new
   end

   def create
     @item = Item.new(item_params)
     # 商品のカラムが存在しているかどうかのif文
     if params[:item][:price].present? && params[:item][:name].present? && params[:item][:explanation].present? && params[:item][:genre_id].present? && params[:item][:image].present?
      # 価格は半角数字0 ~ 9のみ登録可能で、それ以外は登録出来ないようにするif文
       if params[:item][:price].to_s.ord >= 48 && params[:item][:price].to_s.ord <= 57
       # 保存に成功した時のif文
        if @item.save
           redirect_to admin_item_path(@item.id)
           flash[:success] = "商品を登録しました"
        else
           flash[:danger] = "必要情報を入力してください"
           render "admin/items/new"
        end
       else
         flash[:danger] = "価格は半角数字で記入してください"
         redirect_to new_admin_item_path
       end
     else
      # 格カラムが空白で保存されなかった場合
      unless @item.save
         flash[:danger] = "必要情報を入力してください"
         render "admin/items/new"
      end
     end
   end

   def show
     @item = Item.find(params[:id])
     
   end

   def edit
     @item = Item.find(params[:id])
   end

   def update
     @item = Item.find(params[:id])
     # 商品のカラムが存在しているかどうかのif文
     if params[:item][:price].present? && params[:item][:name].present? && params[:item][:explanation].present? && params[:item][:genre_id].present? && params[:item][:image].present?
       # 価格は半角数字のみ登録可能で、それ以外は登録出来ないようにするif文
       if params[:item][:price].to_s.ord >= 48 && params[:item][:price].to_s.ord <= 57
         # 更新に成功した時のif文
         if @item.update(item_params)
           redirect_to admin_item_path(@item.id)
           flash[:success] = "商品を更新しました"
         else
           flash[:danger] = "必要情報を入力してください"
           render "admin/items/edit"
         end
       else
         flash[:danger] = "価格は半角数字で記入してください"
         render "admin/items/edit"
       end
     else
       # 格カラムが空白で更新されなかった場合
       unless @item.update(item_params)
         flash[:danger] = "必要情報を入力してください"
         render "admin/items/edit"
       end
     end
   end

   private

   def item_params
     params.require(:item).permit(:name, :explanation, :image, :genre_id, :price, :is_enabled)
   end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<div class="row">
    <h2>商品編集</h2>
    <%= form_with(model: @item, url: admin_item_path, method: :patch, local: true) do |f| %>
    <!-- エラーメッセージ表示-->
    <% if @item.errors.any? %>
    <h3><%= @item.errors.count %>error occurrence</h3>
    <ul>
        <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
    <% end %>
    <!-- エラーメッセージ表示-->
    <div class="col-xs-5">
      <div class="field">
            <%= image_tag @item.image, size: "100x100" %>
            <%= f.file_field :image, accept: "image/*" %>
      </div>
    </div>
    <div class="col-xs-7">
            <div class="field">
              <%= f.label :商品名 %>
              <%= f.text_field :name, class: "form" %>
            </div>
            <div class="field">
              <%= f.label :商品説明 %>
              <%= f.text_area :explanation %>
            </div>
            <div class="field">
              <%= f.label :ジャンル %>
              <%= f.collection_select(:genre_id, Genre.where(is_enabled: true), :id, :name, prompt: "選択してください") %>
            </div>
            <div class="field">
              <%= f.label :税抜価格 %>
              <%= f.text_field :price %>
            	円
            </div>
            <div class="field">
              <%= f.radio_button :is_enabled, true %>
              <%= f.label :is_enabled, "販売中" %>
              <%= f.radio_button :is_enabled, false %>
              <%= f.label :is_enabled, "売切れ" %>
            </div>
            <div class="actions col-xs-3 col-xs-offset-4">
              <%= f.submit "保存", class: "btn btn-success glyphicon glyphicon-save" %>
            </div>
        <% end %>
    </div>
</div>

app/views/admin/items/index.html.erb
<div class="row">
   <h2>商品一覧</h2>
     <table class="table table-hover table-inverse">
       <thead>
         <tr>
         	<th>商品ID</th>
         	<th>商品名</th>
         	<th>税抜価格</th>
         	<th>ジャンル</th>
         	<th>ステータス</th>
         	<th>コメント数</th>
         </tr>
       </thead>
       <tbody>
       	<% @items.each do |item| %>
       	<tr>
       		<th><%= item.id %></th>
				  <th><%= link_to item.name, admin_item_path(item) %></th>
				  <th><%= item.price %></th>
				  <th><%= item.genre.name %></th>
				  <th><% if item.is_enabled == true %>
					    販売中
					    <% else %>
					    販売停止中
					    <% end %>
				</th>
				<th><%= item.item_comments.count %></th>
				</tr>
				<% end %>
			</tbody>
		</table>
</div>

app/views/admin/items/new.html.erb
<div class="row">
    <%= form_with(model: @item, url: admin_items_path, method: :post, local: true) do |f| %>
     <h2>商品新規登録</h2>
<!-- エラーメッセージ表示-->
    <% if @item.errors.any? %>
    <h3><%= @item.errors.count %>error occurrence</h3>
    <ul>
        <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
    <% end %>
<!-- エラーメッセージ表示-->
      <div class='container'>
        	<div class="field">
        		<h6><%= f.label :・商品画像 %></h6>
                <%= f.file_field :image %>
        	</div>
        	<br />
            <div class="field">
            	<h6><%= f.label :・商品名 %></h6>
            	<%= f.text_field :name, class: "form" %>
            </div>
            <br />
            <div class="field">
            	<h6><%= f.label :・商品説明 %></h6>
            	<%= f.text_area :explanation %>
            </div>
            <br />
            <div class="field">
            	<h6><%= f.label :・ジャンル %></h6>
            	<%= f.collection_select(:genre_id, Genre.where(is_enabled: true), :id, :name, prompt: "選択してください") %>
            </div>
            <br />
            <div class="field">
               <h6><%= f.label :・税抜価格 %></h6>
            	<%= f.text_field :price %>
            	円
            </div>
            <br />
            <div class="field">
            	<%= f.radio_button :is_enabled, true %>
            	<%= f.label :is_enabled, "販売中" %>
                <%= f.radio_button :is_enabled, false %>
                <%= f.label :is_enabled, "売切れ" %>
            </div>
            <%= f.submit "新規登録",class:"btn btn-primary col-xs-12" %>
        </div>
    <% end %>
</div>

app/views/admin/items/show.html.erb
<div class="row">
	<h2>商品詳細</h2>

	<div class="col-xs-5">
		<%= image_tag @item.image, size: "200x200" %>
	</div>
	<div class="col-xs-7">
		<table class="table">
			<tr>
				<th>商品名</th>
				<th><%= @item.name %></th>
			</tr>
			<tr>
				<th>商品説明</th>
				<th><%= @item.explanation %></th>
			</tr>
			<tr>
				<th>ジャンル</th>
				<th><%= @item.genre.name %></th>
			</tr>
			<tr>
				<th>税込価格（税抜価格）</th>
				<th><%= (@item.price * 1.1).to_i %>(<%= @item.price %>)円</th>
			</tr>
			<tr>
				<th>販売ステータス</th>
				<th>
				<% if @item.is_enabled == true %>
				販売中
				<% else %>
				売切れ
				<% end %>
				</th>
			</tr>
		</table>
		<%= render "public/item_comments/index" %>
		<div>
		<%= link_to '編集', edit_admin_item_path(@item), class: "btn btn-success glyphicon glyphicon-wrench pull-right" %>
	    </div>
	</div>
</div>