config/routes.rb
Rails.application.routes.draw do

  # # ユーザー用
    devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
   }
  # 管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
   sessions: "admin/sessions"
  }

 scope module: :public do
  root :to =>"homes#top"

  #ユーザー
   resources :users, only: [:show,:edit,:update,:destroy,:create]
  #商品
   resources :items, only: [:show, :index] do
    #コメント機能
    resources :item_comments, only: [:create, :destroy]
    #いいね機能
    resource :favorites, only: [:create, :destroy]
   end
 end

 namespace :admin do
  root :to =>"homes#top"
  # ジャンル
   resources :genres, only: [:create, :index, :update, :edit,]
  # 商品
   resources :items, only: [:new, :show, :create, :edit, :index, :update]
 end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<p class="footer-text">shiritaide@syouhinn</p>

app/views/layouts/_header_admin.html.erb
     <li class="nav-item">
       <%= link_to "商品一覧", admin_items_path %>
     </li>
     <li class="nav-item">
       <%= link_to "商品追加", new_admin_item_path %>
     </li>
     <li class="nav-item">
       <%= link_to "ジャンル一覧", admin_genres_path %>
     </li>
     <li class="nav-item">
       <%= link_to "ログアウト", destroy_admin_session_path %>
     </li>

app/views/layouts/_header_logout.html.erb
    <li class="nav-item">
    <%= link_to "商品一覧", items_path %>
    </li>
    <li class="nav-item">
      <%= link_to "新規登録", new_user_registration_path %>
    </li>
    <li class="nav-item">
      <%= link_to "会員ログイン", new_user_session_path %>
    </li>
    <li class="nav-item">
      <%= link_to "管理者ログイン", new_admin_session_path %>
    </li>

app/views/layouts/_header_public.html.erb
      <li class="nav-item">
        <%= link_to "マイページ", user_path(current_user) %>
      </li>
      <li class="nav-item">
        <%= link_to "商品一覧", items_path %>
      </li>
      <li class="nav-item">
        <%= link_to "ログアウト", destroy_user_session_path %>
      </li>

app/views/layouts/_search.html.erb
<div class="search_form">
   <%= form_with url: search_path, local: true, method: :get do |f| %>
     <%= f.text_field :word %>
     <%= f.select :range, options_for_select(['商品']) %>
     <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
     <%= f.submit "検索", class: "btn btn-primary" %>
   <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shiritaidesyouhinn</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark navbar-lightd">
        <div class="container">
          <a class="navbar-brand p-3" href="/"><span>知りたいでしょうひん</span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
           <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <%= render 'layouts/header_public' %>
              <% elsif admin_signed_in? %>
                <%= render 'layouts/header_admin' %>
              <% else %>
                <%= render 'layouts/header_logout' %>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <div class="container main-container">
       <p id="notice"><%= notice %></p>
      　<%= yield %>
      </div>
    </main>
     <footer>
       <div class='container mt-5'>
         <div class="row no-gutters">
           <div class='mx-auto'>
            <%= render 'layouts/footer' %>
          </div>
         </div>
       </div>
     </footer>
  </body>
</html>